# Generated by Django 5.2.14 on 2026-06-17 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import posthog.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "1223_remove_ducklakecatalog_cross_account_fields"),
        ("posthog_ai", "0003_conversation_topic"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationAttachment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted", models.BooleanField(blank=True, default=False, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=posthog.models.utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conversation_id",
                    models.UUIDField(help_text="Conversation UUID this attachment is scoped to."),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Sanitized display filename supplied by the user.",
                        max_length=255,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        help_text="Server-detected image MIME type. Only image/png and image/jpeg are supported.",
                        max_length=32,
                    ),
                ),
                (
                    "byte_size",
                    models.PositiveIntegerField(help_text="Validated object size in bytes."),
                ),
                (
                    "object_key",
                    models.CharField(
                        help_text="Private object-storage key for the uploaded image.",
                        max_length=512,
                        unique=True,
                    ),
                ),
                (
                    "attachment_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("attached", "Attached")],
                        default="pending",
                        help_text="Lifecycle state of the attachment.",
                        max_length=20,
                    ),
                ),
                (
                    "attached_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the attachment was sent in a message.",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User that removed the attachment, if removed explicitly.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="posthog.team"),
                ),
            ],
            options={
                "db_table": "posthog_ai_conversationattachment",
                "indexes": [
                    models.Index(
                        fields=[
                            "team",
                            "conversation_id",
                            "deleted",
                            "attachment_status",
                        ],
                        name="phai_att_team_conv_status_idx",
                    ),
                    models.Index(
                        fields=["team", "created_by", "deleted"],
                        name="phai_att_team_user_del_idx",
                    ),
                ],
            },
        ),
    ]
