# Generated by Django 5.2.14 on 2026-06-19 05:08

import django.db.models.deletion
import posthog.models.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posthog", "1223_remove_ducklakecatalog_cross_account_fields"),
        ("posthog_ai", "0003_conversation_topic"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=posthog.models.utils.UUIDT,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("conversation_id", models.UUIDField()),
                ("file_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=32)),
                ("size", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("object_path", models.CharField(max_length=255, unique=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="posthog.team"
                    ),
                ),
            ],
            options={
                "db_table": "ee_conversationattachment",
                "indexes": [
                    models.Index(
                        fields=["team", "creator", "conversation_id"],
                        name="ee_conversa_team_id_c97e8e_idx",
                    )
                ],
            },
        ),
    ]
